# Model Training on Cleaned Data

In [8]:
import pandas as pd

In [9]:
# loading dataset 
#df = pd.read_csv(r'/content/drive/My Drive/ML/clean_tweets.csv')
df = pd.read_csv('clean_tweets.csv')
df.head()

target  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY _TheSpecialOne_  \
0       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   scotthamilton   
1       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY        mattycus   
2       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         ElleCTF   
3       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          Karoli   
4       0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY        joy_wolf   

                                              tweets  \
0  is upset that he can't update his Facebook by ...   
1  @Kenichan I dived many times for the ball. Man...   
2    my whole body feels itchy and like its on fire    
3  @nationwideclass no, it's not behaving at all....   
4                      @Kwesidei not the whole crew    

                                        clean_tweets  
0  upset ca n't updat facebook text ... might cri...  
1  i dive mani time ball . manag save 50 % the re...  
2                    whole bodi feel itchi like fire  
3             , 's behav . 'm mad . ? i ca n't see .  
4                                         whole crew

In [10]:
df['clean_tweets'] = df['clean_tweets'].astype(str)

In [11]:
df['clean_tweets'].head()

0    upset ca n't updat facebook text ... might cri...
1    i dive mani time ball . manag save 50 % the re...
2                      whole bodi feel itchi like fire
3               , 's behav . 'm mad . ? i ca n't see .
4                                           whole crew
Name: clean_tweets, dtype: object

In [12]:
for i in range(len(df['target'])):
  if df['target'][i]==4:
    df['target'][i] = 1
    

C:\Users\Shubham\AppData\Local\Temp\ipykernel_8580\3846377706.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][i] = 1


In [13]:
df[df['target']==1]

target  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  \
799999        1  1467822272  Mon Apr 06 22:22:45 PDT 2009  NO_QUERY   
800000        1  1467822273  Mon Apr 06 22:22:45 PDT 2009  NO_QUERY   
800001        1  1467822283  Mon Apr 06 22:22:46 PDT 2009  NO_QUERY   
800002        1  1467822287  Mon Apr 06 22:22:46 PDT 2009  NO_QUERY   
800003        1  1467822293  Mon Apr 06 22:22:46 PDT 2009  NO_QUERY   
...         ...         ...                           ...       ...   
1599994       1  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599995       1  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996       1  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997       1  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998       1  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

         _TheSpecialOne_                                             tweets  \
799999             ersle       I LOVE @Health4UandPets u guys r the best!!    
800000          becca210  im meeting up with one of my besties tonight! ...   
800001         Wingman29  @DaRealSunisaKim Thanks for the Twitter add, S...   
800002         katarinka  Being sick can be really cheap when it hurts t...   
800003       _EmilyYoung    @LovesBrooklyn2 he has that effect on everyone    
...                  ...                                                ...   
1599994  AmandaMarie1028  Just woke up. Having no school is the best fee...   
1599995      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...   
1599996           bpbabe  Are you ready for your MoJo Makeover? Ask me f...   
1599997     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...   
1599998   RyanTrevMorris  happy #charitytuesday @theNSPCC @SparksCharity...   

                                              clean_tweets  
799999                             i love u guy r best ! !  
800000   im meet one besti tonight ! cant wait ! ! - gi...  
800001   thank twitter add , sunisa ! i got meet hin sh...  
800002   be sick realli cheap hurt much eat real food p...  
800003                                      effect everyon  
...                                                    ...  
1599994             just woke . have school best feel ever  
1599995  thewdb.com - veri cool hear old walt interview...  
1599996                 are readi mojo makeov ? ask detail  
1599997  happi 38th birthday boo alll time ! ! ! tupac ...  
1599998                             happi # charitytuesday  

[800000 rows x 7 columns]

In [14]:
df[df['target']==0]

target  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  \
0            0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
1            0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
2            0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
3            0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4            0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY   
...        ...         ...                           ...       ...   
799994       0  2329205009  Thu Jun 25 10:28:28 PDT 2009  NO_QUERY   
799995       0  2329205038  Thu Jun 25 10:28:28 PDT 2009  NO_QUERY   
799996       0  2329205473  Thu Jun 25 10:28:30 PDT 2009  NO_QUERY   
799997       0  2329205574  Thu Jun 25 10:28:30 PDT 2009  NO_QUERY   
799998       0  2329205794  Thu Jun 25 10:28:31 PDT 2009  NO_QUERY   

       _TheSpecialOne_                                             tweets  \
0        scotthamilton  is upset that he can't update his Facebook by ...   
1             mattycus  @Kenichan I dived many times for the ball. Man...   
2              ElleCTF    my whole body feels itchy and like its on fire    
3               Karoli  @nationwideclass no, it's not behaving at all....   
4             joy_wolf                      @Kwesidei not the whole crew    
...                ...                                                ...   
799994        dandykim  Sick  Spending my day laying in bed listening ...   
799995         bigenya                                    Gmail is down?    
799996        LeeLHoke                      rest in peace Farrah! So sad    
799997    davidlmulder  @Eric_Urbane Sounds like a rival is flagging y...   
799998      tpchandler  has to resit exams over summer...  wishes he w...   

                                             clean_tweets  
0       upset ca n't updat facebook text ... might cri...  
1       i dive mani time ball . manag save 50 % the re...  
2                         whole bodi feel itchi like fire  
3                  , 's behav . 'm mad . ? i ca n't see .  
4                                              whole crew  
...                                                   ...  
799994                      sick spend day lay bed listen  
799995                                            gmail ?  
799996                          rest peac farrah ! so sad  
799997         sound like rival flag ad . not much though  
799998  resit exam summer ... wish work harder first y...  

[799999 rows x 7 columns]

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
#vectorizer = CountVectorizer(max_df=0.90, min_df=1, stop_words='english')
# bag-of-words feature matrix

vectorizer = CountVectorizer(max_features=8, stop_words='english')

vectorized_data = vectorizer.fit_transform(df['clean_tweets'])

In [62]:
vectorized_data

<1599999x8 sparse matrix of type '<class 'numpy.int64'>'
	with 603987 stored elements in Compressed Sparse Row format>

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

In [64]:
X_train, X_test, y_train, y_test = train_test_split( vectorized_data, df['target'], test_size=0.2, random_state=42)
import numpy as np

In [65]:

lreg = LogisticRegression()
lreg.fit(X_train, y_train) # training the model

prediction = lreg.predict_proba(X_test) # predicting on the validation set
prediction_int = prediction[:,1] >= 0.45 # if prediction is greater than or equal to 0.3 than 1 else 0
prediction_int = prediction_int.astype(np.int)

f1_score(y_test, prediction_int) # calculating f1 score

C:\Users\Shubham\AppData\Local\Temp\ipykernel_8580\1018308769.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  prediction_int = prediction_int.astype(np.int)


0.6650415225065613

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction_int)

0.5238

In [67]:
f1_score(y_test, prediction_int) # calculating f1 score

0.6650415225065613

In [68]:
print(prediction_int)

[1 0 1 ... 1 1 1]


In [69]:
tweet = np.array(["To completely change the character and nature of the lions on Ashoka's pillar at Sarnath is nothing but a brazen insult to India’s National Symbol! "])

In [70]:
tweet.shape

(1,)

In [71]:
df1 = pd.DataFrame(tweet)
df1.head()

0
0  To completely change the character and nature ...

In [72]:
df1[0]

0    To completely change the character and nature ...
Name: 0, dtype: object

In [73]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=8, stop_words='english')
# bag-of-words feature matrix
x = vectorizer.fit_transform(df1[0])

In [74]:
prediction1 = lreg.predict_proba(x) #predicting on the validation set

In [75]:
prediction1

array([[0.1495394, 0.8504606]])

In [76]:
prediction_int1 = prediction1[:,1] >= 0.45 # if prediction is greater than or equal to 0.3 than 1 else 0
#prediction_int1 = prediction_int1.astype(np.int)

In [77]:
prediction_int1

array([ True])

In [78]:
prediction_int1

array([ True])

In [79]:
import pickle
pickle.dump(lreg, open('model.pkl','wb'))

In [80]:
pickle_in = open('model.pkl',"rb")
classifier=pickle.load(pickle_in)

In [ ]:
classifier.predict(df[0])